#!/bin/bash

# Script to manually verify and apply RM Sotheby's scraper fixes
# Run this after reviewing the changes in RM_SOTHEBYS_FIXES_SUMMARY.md

echo "RM Sotheby's Scraper Fixes - Manual Application Guide"
echo "======================================================"
echo ""
echo "The AI parsing changes have been SUCCESSFULLY applied to:"
echo "  ✓ /Users/brad/Code2/finds/src/services/ai/global-sales.service.ts"
echo ""
echo "The following changes still need to be applied manually to:"
echo "  ⚠ /Users/brad/Code2/finds/src/lib/auction-scrapers.ts"
echo ""
echo "REASON: File was modified by linter during editing session"
echo ""
echo "------------------------------------------------------------"
echo "Change 1: Fix title extraction (around line 583)"
echo "------------------------------------------------------------"
echo ""
echo "FIND:"
echo "  const title = lotPart.split('-').slice(1).join(' ').replace(/-/g, ' ') || 'RM Sotheby\\'s Lot'"
echo ""
echo "REPLACE WITH:"
echo "  // Remove lot number prefix (e.g., r0001-, n0001-) to get clean title"
echo "  const title = lotPart.replace(/^[a-z]\\d+-/i, '').replace(/-/g, ' ') || 'RM Sotheby\\'s Lot'"
echo ""
echo "------------------------------------------------------------"
echo "Change 2: Update URL target (around line 620-628)"
echo "------------------------------------------------------------"
echo ""
echo "FIND:"
echo "  console.log('[Scraper] RM Sotheby\\'s: Navigating to results page...')"
echo "  await page.goto('https://rmsothebys.com/en/results', {"
echo ""
echo "REPLACE WITH:"
echo "  // Recent completed auctions - rotate through these to get variety"
echo "  // Format: {code}24 = 2024, {code}25 = 2025"
echo "  const recentAuctions = ["
echo "    'mo24', // Monterey 2024 (August) - major auction"
echo "    'pa24', // Paris 2024"
echo "    'az25', // Arizona 2025 (January)"
echo "    'mi25', // Miami 2025 (February)"
echo "    'pa25', // Paris 2025"
echo "    'mo25', // Monterey 2025 (August)"
echo "  ]"
echo ""
echo "  // Pick a random recent auction to get variety"
echo "  const auctionCode = recentAuctions[Math.floor(Math.random() * recentAuctions.length)]"
echo "  const auctionUrl = \`https://rmsothebys.com/auctions/\${auctionCode}/lots/\`"
echo ""
echo "  console.log(\`[Scraper] RM Sotheby's: Navigating to \${auctionCode} auction results...\`)"
echo ""
echo "  await page.goto(auctionUrl, {"
echo ""
echo "------------------------------------------------------------"
echo "Change 3: Increase Angular wait time (around line 631-643)"
echo "------------------------------------------------------------"
echo ""
echo "FIND:"
echo "  // Wait for Angular app to load"
echo "  await new Promise(resolve => setTimeout(resolve, 5000))"
echo ""
echo "  // Scroll to trigger lazy loading"
echo "  for (let i = 0; i < 3; i++) {"
echo "    await page.evaluate(() => window.scrollBy(0, 500))"
echo "    await randomDelay()"
echo "  }"
echo ""
echo "REPLACE WITH:"
echo "  // Wait for Angular app to load and render lot data"
echo "  // RM Sotheby's uses Angular - need extra time for lot data to populate"
echo "  console.log('[Scraper] RM Sotheby\\'s: Waiting for Angular to render lots...')"
echo "  await new Promise(resolve => setTimeout(resolve, 8000))"
echo ""
echo "  // Try to wait for lot links to appear in the DOM"
echo "  try {"
echo "    await page.waitForSelector('a[href*=\"/lots/\"]', { timeout: 10000 })"
echo "    console.log('[Scraper] RM Sotheby\\'s: Lot links detected')"
echo "  } catch {"
echo "    console.log('[Scraper] RM Sotheby\\'s: Warning - No lot links found after waiting')"
echo "  }"
echo ""
echo "  // Scroll to trigger lazy loading of more lots"
echo "  for (let i = 0; i < 4; i++) {"
echo "    await page.evaluate(() => window.scrollBy(0, 600))"
echo "    await randomDelay()"
echo "  }"
echo ""
echo "------------------------------------------------------------"
echo "Change 4: Improve URL extraction (around line 647-656)"
echo "------------------------------------------------------------"
echo ""
echo "FIND:"
echo "  const urls = await page.evaluate(() => {"
echo "    const links = document.querySelectorAll('a[href]')"
echo "    return Array.from(links)"
echo "      .map(link => (link as HTMLAnchorElement).href)"
echo "      .filter(href => {"
echo "        if (!href || !href.includes('rmsothebys.com')) {return false}"
echo "        // Match URLs like /auctions/pt25/lots/n0001-1965-ferrari-275/"
echo "        return /\\/auctions\\/[a-z0-9]+\\/lots\\/[a-z0-9]+-/.test(href)"
echo "      })"
echo "  })"
echo ""
echo "  const uniqueUrls = Array.from(new Set(urls)).slice(0, 20)"
echo "  console.log(\`[Scraper] RM Sotheby's: Found \${uniqueUrls.length} URLs\`)"
echo ""
echo "REPLACE WITH:"
echo "  const urls = await page.evaluate(() => {"
echo "    const links = document.querySelectorAll('a[href]')"
echo "    const lotUrls: string[] = []"
echo ""
echo "    links.forEach(link => {"
echo "      const href = (link as HTMLAnchorElement).href"
echo "      if (!href || !href.includes('rmsothebys.com')) {return}"
echo ""
echo "      // Match URLs like /auctions/mo24/lots/r0207-2015-ferrari-laferrari/"
echo "      // Lot IDs start with letter + numbers (r0001, n0001, etc.)"
echo "      if (/\\/auctions\\/[a-z0-9]+\\/lots\\/[a-z]\\d+-[a-z0-9-]+/i.test(href)) {"
echo "        lotUrls.push(href)"
echo "      }"
echo "    })"
echo ""
echo "    return lotUrls"
echo "  })"
echo ""
echo "  const uniqueUrls = Array.from(new Set(urls)).slice(0, 20)"
echo "  console.log(\`[Scraper] RM Sotheby's: Found \${uniqueUrls.length} lot URLs from \${auctionCode}\`)"
echo ""
echo "------------------------------------------------------------"
echo "After applying changes, test with:"
echo "------------------------------------------------------------"
echo ""
echo "  USE_PUPPETEER=true npm run scrape-auctions"
echo ""
echo "Expected: 10-20 lot URLs found with clean titles (no r0001- prefixes)"
echo ""
echo "For detailed documentation, see:"
echo "  - RM_SOTHEBYS_SCRAPER_FIXES.md (technical details)"
echo "  - RM_SOTHEBYS_FIXES_SUMMARY.md (implementation summary)"
echo "  - src/lib/auction-scrapers-rmsothebys-fixed.ts (reference implementation)"
echo ""
